### ISSUE TITLE
Does it search code using search string in description?

### ISSUE THREAD

**Issue by analyticalpicasso** [StefanoTrv/simple_icd_10_CM#2]
Hello, 

Its a very nice library you have create to navigate in icd10 xml file. Does it also have flexibility to search in code description using specific search string?

Thanks.

**Comment by StefanoTrv** [comment]
Hi.
It's not a default functionality in the library, but you can use the `get_all_codes()` function to get the list of all the codes and then create a list of all the descriptions using the `get_description()` function. You can then search in this second list for a specific pattern.

**Comment by analyticalpicasso** [comment]
ok. Thanks.
