### ISSUE TITLE
python version w/ conda

### ISSUE THREAD

**Issue by bdp-utah1** [StefanoTrv/simple_icd_10_CM#4]
Is it possible to update the conda repo for compatibility with new Python versions, such as python 3.10? I had to create a new conda env with python 3.8 in order to install this package.

`$ conda install -c stefanotrv simple_icd_10_cm`
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - simple_icd_10_cm -> python[version='>=3.8,<3.9.0a0']

Your python: python=3.10

----
Cheers!

**Comment by StefanoTrv** [comment]
Thank you for informing me about this issue.
I'm planning to make a new version of the library with some small improvements, as soon as I have some time. When I release this new version to anaconda.org the problem should be fixed.
I hope to be able to do this soon.

**Comment by StefanoTrv** [comment]
Hi, sorry for the long wait. The latest version of the library on anconda.org now uses Python 3.11.
Please inform me if there are more problems, since anaconda's tools for creating packages have become very buggy.
