### ISSUE TITLE
Potentially add type hints for public functions

### ISSUE THREAD

**Issue by JosephSBoyle** [StefanoTrv/simple_icd_10_CM#8]
Hi Stefano, thank you for your library. It's been really convenient to work with and has saved me many hours of data wrangling!

I'd like to contribute some type hints to the public interface of the library, which I think would enhance developer ergonomics even further. What do you think?

@StefanoTrv

**Comment by StefanoTrv** [comment]
Hi Joseph,
thank you for your kind comment and the offer to contribute. I think type hints would be a useful addition. Feel free to start working on it, and if you need any help, just let me know.

**Comment by JosephSBoyle** [comment]
Awesome, I've opened a PR here: https://github.com/StefanoTrv/simple_icd_10_CM/pull/9.
Closing this issue!:)
